// Code generated by "stringer -type=FieldBiome"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Sea-0]
	_ = x[Plains-1]
	_ = x[Forest-2]
	_ = x[Ores-3]
	_ = x[FieldBiomeCount-4]
}

const _FieldBiome_name = "SeaPlainsForestOresFieldBiomeCount"

var _FieldBiome_index = [...]uint8{0, 3, 9, 15, 19, 34}

func (i FieldBiome) String() string {
	if i < 0 || i >= FieldBiome(len(_FieldBiome_index)-1) {
		return "FieldBiome(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FieldBiome_name[_FieldBiome_index[i]:_FieldBiome_index[i+1]]
}
